-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GeneratedGraphql.Object.CatType exposing (id, url)

import GeneratedGraphql.InputObject
import GeneratedGraphql.Interface
import GeneratedGraphql.Object
import GeneratedGraphql.Scalar
import GeneratedGraphql.ScalarCodecs
import GeneratedGraphql.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Url of the image
-}
url : SelectionSet String GeneratedGraphql.Object.CatType
url =
    Object.selectionForField "String" "url" [] Decode.string


{-| The id of the image
-}
id : SelectionSet String GeneratedGraphql.Object.CatType
id =
    Object.selectionForField "String" "id" [] Decode.string
