-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GeneratedGraphql.Mutation exposing (AddVoteRequiredArguments, addVote)

import GeneratedGraphql.InputObject
import GeneratedGraphql.Interface
import GeneratedGraphql.Object
import GeneratedGraphql.Scalar
import GeneratedGraphql.ScalarCodecs
import GeneratedGraphql.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias AddVoteRequiredArguments =
    { input : GeneratedGraphql.InputObject.VoteInput }


addVote : AddVoteRequiredArguments -> SelectionSet (Maybe String) RootMutation
addVote requiredArgs =
    Object.selectionForField "(Maybe String)" "addVote" [ Argument.required "input" requiredArgs.input GeneratedGraphql.InputObject.encodeVoteInput ] (Decode.string |> Decode.nullable)
