-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GeneratedGraphql.Object exposing (CatType(..), VoteUIType(..))


type CatType
    = CatType


type VoteUIType
    = VoteUIType
