-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GeneratedGraphql.Query exposing (allVotes, cats, topFive, totalVotes)

import GeneratedGraphql.InputObject
import GeneratedGraphql.Interface
import GeneratedGraphql.Object
import GeneratedGraphql.Scalar
import GeneratedGraphql.ScalarCodecs
import GeneratedGraphql.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


cats : SelectionSet decodesTo GeneratedGraphql.Object.CatType -> SelectionSet (List decodesTo) RootQuery
cats object_ =
    Object.selectionForCompositeField "cats" [] object_ (identity >> Decode.list)


allVotes : SelectionSet decodesTo GeneratedGraphql.Object.VoteUIType -> SelectionSet (List decodesTo) RootQuery
allVotes object_ =
    Object.selectionForCompositeField "allVotes" [] object_ (identity >> Decode.list)


topFive : SelectionSet decodesTo GeneratedGraphql.Object.VoteUIType -> SelectionSet (List decodesTo) RootQuery
topFive object_ =
    Object.selectionForCompositeField "topFive" [] object_ (identity >> Decode.list)


totalVotes : SelectionSet Int RootQuery
totalVotes =
    Object.selectionForField "Int" "totalVotes" [] Decode.int
